# Paige Clemons (pclemon)
# Lab Section 5
# Homework 3
# Due: 10/28/18

default:cpsc2150/connectX/
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/IGameBoard.java cpsc2150/connectX/GameBoardMem.java
run:cpsc2150/connectX/
	java cpsc2150.connectX.Connect4Game cpsc2150.connectX.GameBoard cpsc2150.connectX.IGameBoard cpsc2150/connectX/GameBoard.java
clean:
	rm -f cpsc2150/connectX/*.class
