# Paige Clemons (pclemon)
# Lab Section 5
# Homework 1
# Due: 9/23/18

default:cpsc2150/connectX/
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java
run:cpsc2150/connectX/
	java cpsc2150.connectX.Connect4Game cpsc2150.connectX.GameBoard
clean:
	rm -f cpsc2150/connectX/*.class
