# Paige Clemons (pclemon)
# Lab Section 5
# Homework 2
# Due: 10/10/18

default:cpsc2150/connectX/
	javac cpsc2150/connectX/Connect4Game.java cpsc2150/connectX/GameBoard.java cpsc2150/connectX/IGameBoard.java
run:cpsc2150/connectX/
	java cpsc2150.connectX.Connect4Game cpsc2150.connectX.GameBoard cpsc2150.connectX.IGameBoard
clean:
	rm -f cpsc2150/connectX/*.class
